# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goup < Formula
  desc ""
  homepage ""
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/RyotaroSeto/goup/releases/download/v0.2.0/goup_Darwin_x86_64.tar.gz"
      sha256 "46fbff320e2fddb34538f9861b298136e0d796e51583dae696c9800b0f9bce42"

      def install
        bin.install "goup"
      end
    end
    on_arm do
      url "https://github.com/RyotaroSeto/goup/releases/download/v0.2.0/goup_Darwin_arm64.tar.gz"
      sha256 "684c090c6d29522144ece365f3b06029d5a58628a52122c34a38e5eba4bcfa0f"

      def install
        bin.install "goup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/RyotaroSeto/goup/releases/download/v0.2.0/goup_Linux_x86_64.tar.gz"
        sha256 "a4995492a013a0e6a28e40e970b4aafa2de5354feeb1a83cb5b69f8c8b4c3fdf"

        def install
          bin.install "goup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/RyotaroSeto/goup/releases/download/v0.2.0/goup_Linux_arm64.tar.gz"
        sha256 "c2290cafb22e49fb72589827ad91990e0ff55238675328e092c80dcab012a501"

        def install
          bin.install "goup"
        end
      end
    end
  end
end
