# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goup < Formula
  desc ""
  homepage ""
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/RyotaroSeto/goup/releases/download/v0.4.0/goup_Darwin_x86_64.tar.gz"
      sha256 "b09f9993c0ffa330a18e052e0c92aaf1246bea7bb774c953e1c769d0c9e04493"

      def install
        bin.install "goup"
      end
    end
    on_arm do
      url "https://github.com/RyotaroSeto/goup/releases/download/v0.4.0/goup_Darwin_arm64.tar.gz"
      sha256 "733ef3a60b31d3d8f67bddcb319eeb41a75288f1ba8cce353287b83dfe670fd2"

      def install
        bin.install "goup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/RyotaroSeto/goup/releases/download/v0.4.0/goup_Linux_x86_64.tar.gz"
        sha256 "b0dd3e0b881d6f93501a08cd793001f79d75519ce87b1fe2f940246c6f8eefb2"

        def install
          bin.install "goup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/RyotaroSeto/goup/releases/download/v0.4.0/goup_Linux_arm64.tar.gz"
        sha256 "00d5f0ce827bc0fd0af2ef9166a0b3c0806a79f4d9070f099b361671cf12dd2d"

        def install
          bin.install "goup"
        end
      end
    end
  end
end
