# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neko < Formula
  desc ""
  homepage ""
  version "1.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/RyotaroSeto/neko/releases/download/1.0.7/neko_Darwin_arm64.tar.gz"
      sha256 "ed245d8de274217dfdbf19ea87a01f1845a9d155c8ee829930469d3cfe47ad7f"

      def install
        bin.install "neko"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RyotaroSeto/neko/releases/download/1.0.7/neko_Darwin_x86_64.tar.gz"
      sha256 "5353a0707c4c7e185343c0a5c877792bd5857097a3ee6b75730f816c056bec68"

      def install
        bin.install "neko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RyotaroSeto/neko/releases/download/1.0.7/neko_Linux_x86_64.tar.gz"
      sha256 "7694709e47c59be6f965da960f9a9f7b9bf4009281880730ba01c54bf87cf9df"

      def install
        bin.install "neko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RyotaroSeto/neko/releases/download/1.0.7/neko_Linux_arm64.tar.gz"
      sha256 "57a0a4866ae24493ad00985f2b83fcfef836630a32dcf09daf2cd860df69cb34"

      def install
        bin.install "neko"
      end
    end
  end
end
