# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neko < Formula
  desc ""
  homepage ""
  version "1.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RyotaroSeto/neko/releases/download/1.0.8/neko_Darwin_x86_64.tar.gz"
      sha256 "72cb6488afba8e660a338c0739c6ecb2db49a292860bfc975a648bc1452fc243"

      def install
        bin.install "neko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RyotaroSeto/neko/releases/download/1.0.8/neko_Darwin_arm64.tar.gz"
      sha256 "008c94020f976a1f8f9da7d4b604ae1e1aad84822817d59f48f8a29f18bd0dac"

      def install
        bin.install "neko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RyotaroSeto/neko/releases/download/1.0.8/neko_Linux_arm64.tar.gz"
      sha256 "fc5c66bbb5a6152b78bd46ff9c2c42444e2f2ab61084f69c3a9661c825248368"

      def install
        bin.install "neko"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RyotaroSeto/neko/releases/download/1.0.8/neko_Linux_x86_64.tar.gz"
      sha256 "110499ac31d6bb250d6b092b4195ac732db5f0837d45254348c63fd95a7fcc04"

      def install
        bin.install "neko"
      end
    end
  end
end
